### ISSUE TITLE
Alterações no Banco de Dados

### ISSUE THREAD

**Issue by lucasljf** [prof-lucas-faria/gerenciadoravaliacoes#12]
Registrar aqui as alterações que precisam ser feitas no banco de dados.

**Comment by lucasljf** [comment]
Tabela **criterio**:
- Adicionar o campo **nome**.

Tabela **area**:
- Adicionar o campo **descricao**.

**Comment by lucasljf** [comment]
Tabela **evento**:
- Inserir campo para logotipo.

**Comment by lucasljf** [comment]
Alterar todos os campos INT para BIGINT.

**Comment by lucasljf** [comment]
Rever o relacionamento entre **Avaliador** e **Area**: alterar para relação N:N

**Comment by gustavofaquim** [comment]
Trocar *quantidade de avaliadores* da tabela Evento para a tabela Categoria.

**Comment by gustavofaquim** [comment]
Organizar sequência de criação das tabelas no script do banco.
