### ISSUE TITLE
Alterações no Diagrama de Classes

### ISSUE THREAD

**Issue by lucasljf** [prof-lucas-faria/gerenciadoravaliacoes#13]
Registrar aqui as alterações que precisam ser feitas no Diagrama de Classes.

**Comment by lucasljf** [comment]
Verificar a multiplicidade **Avaliador** - **Avaliacao**

**Comment by MarcosACLima** [comment]
Concluída as alteração do diagrama de classe de multiplicidade e implementação das demais classes do pacote model a interface Entidade
