### ISSUE TITLE
EventoDAO

### ISSUE THREAD

**Issue by lucasljf** [prof-lucas-faria/gerenciadoravaliacoes#20]
Fique atento ao nome correto do arquivo. Todos os DAOs devem implementar InterfaceDAO e, consequentemente, implementar os métodos.

Antes de subir suas alterações, você deve testar TODOS os métodos que implementou. Fique à vontade para criar uma classe de teste com o nome: NomeDaClasseTeste.

**Comment by marcosadf** [comment]
Crie um método "public Entidade pesquisarIdProjeto(Entidade entidade)" que retorne o Evento que contem aquele projeto.

**Comment by lucasljf** [comment]
Corrigir o método que lista tudo para que funcione com a entidade Organizador.
Direcionado para: @faquimgustavo
