### ISSUE TITLE
Popular a base de dados

### ISSUE THREAD

**Issue by lucasljf** [prof-lucas-faria/gerenciadoravaliacoes#23]
Criar scripts separados para cada tabela do banco. Tentar definir uma quantidade de inserções que permita testar funções de listagem. Ficar atento ao diagrama do banco. Salve os scripts criados em um pasta própria dentro do diretório "documentacao".

**Comment by JClaudioo** [comment]
Concluido, existem arquivos para todas as tabelas e um arquivo geral para add tudo de uma vez
