### ISSUE TITLE
Criar as classes: Pessoa, Organizador, Area, Criterio

### ISSUE THREAD

**Issue by lucasljf** [prof-lucas-faria/gerenciadoravaliacoes#5]
Orientar-se com o diagrama do banco de dados. É necessário aguardar até que outro colaborador crie a estrutura de pacotes.

**Comment by lucasljf** [comment]
Alterar para que essas classes implementem a interface **Entidade**. A classe Pessoa não deve ser alterada.

**Comment by MarcosWinicios** [comment]
Olá...Preciso dos metodos getters e setters para fazer o CriteioDAO

**Comment by MarciaLinhares** [comment]
Acrescentar o atributo descrição na classe Area

**Comment by MarcosWinicios** [comment]
Mudar tipo de notas minima e maxima para double

**Comment by MarciaLinhares** [comment]
Mudar na classe Area: mudar id de int para long e editar idEvento

**Comment by MarcosWinicios** [comment]
Criar atributo "nome" na classe Criterio

**Comment by MarcosWinicios** [comment]
Criar instancia de Categoria na Classe Criterio

**Comment by MarcosWinicios** [comment]
Preciso de Construtores com os parametros: 
1 - Descricao, notaMinima,notaMaxima,nome.

2 - Id, Descricao, NotaMinima, NotaMaxima, Nome

**Comment by MarcosWinicios** [comment]
Preciso de um Construtor Vazio
